import { Inter } from "next/font/google";
import "./globals.css";
import StoryblokProvider from "@/app/[lang]/_components/providers/StoryblokProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Storyblok Next.js Blog",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <StoryblokProvider>
            <html lang="en">
                <body className={`${inter.className} antialiased`}>{children}</body>
            </html>
        </StoryblokProvider>
    );
}
